Feature/validation on view time page
7ep/r3z pull request #85
Opened 2021-02-17 21:03 UTC by 7ep

2021-02-17 21:12 UTC, 7ep commented on build.gradle
> +    maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
It's always faster to run the UI tests in parallel.  Not so much the other kinds though.

2021-02-17 21:12 UTC, 7ep commented on src/main/kotlin/coverosR3z/authentication/persistence/AuthenticationPersistence.kt
> +    override fun createUser(name: UserName, hash: Hash, salt: Salt, employeeId: EmployeeId) : User {
all users now have an employee, it's non-nullable (good job @coveros-matt-taylor )

2021-02-17 21:12 UTC, 7ep commented on src/main/kotlin/coverosR3z/misc/types/Date.kt
> +val earliestAllowableDate = LocalDate.of(1980, 1, 1)
making these available across the system - so tests can assert we do properly

2021-02-17 21:12 UTC, 7ep commented on src/main/kotlin/coverosR3z/misc/types/Date.kt
> +     * Chrome format "MMddYYYY"
found a little bug - uppercase D is the number of the day in the year, not the month

2021-02-17 21:12 UTC, 7ep commented on src/main/kotlin/coverosR3z/server/utility/ServerUtilities.kt
> +                    logger.logTrace { "client closed their connection while we were waiting to read from the socket" }
more properly handling the case when a client shuts down their connection to us, we'll pass this up to be handled closer to the top loop of the server

2021-02-17 21:12 UTC, 7ep commented on src/main/kotlin/coverosR3z/timerecording/api/ViewTimeAPI.kt
> +                <input readonly name="${Elements.TIME_INPUT.getElemName()}" type="number" value="${it.time.getHoursAsString()}" />
no need for validation on read-only inputs

2021-02-17 21:12 UTC, 7ep commented on src/main/kotlin/coverosR3z/timerecording/api/ViewTimeAPI.kt
> +                <input name="${Elements.DATE_INPUT.getElemName()}" type="date" min="$earliestAllowableDate" max="$latestAllowableDate" value="${safeAttr(it.date.stringValue)}" />
See? We can use constants.  They're nice.

2021-02-17 21:12 UTC, 7ep commented on src/main/kotlin/coverosR3z/timerecording/types/Employee.kt
> +        require(value >= 0) { minEmployeeIdMsg }
now we allow 0 as an employee id - but only for the system user

2021-02-17 21:12 UTC, 7ep commented on src/test/kotlin/coverosR3z/persistence/PureMemoryDatabaseTests.kt
> -    fun testSerialization_UserWithNullEmployee() {
obsolete test - no longer possible to have a null employee

2021-02-17 21:12 UTC, 7ep commented on src/test/kotlin/coverosR3z/server/RegisterAPITests.kt
> -    @Category(APITestCategory::class)
obsolete

2021-02-17 21:12 UTC, 7ep commented on src/test/kotlin/coverosR3z/timerecording/EnterTimeAPITests.kt
> -    @Category(APITestCategory::class)
obsolete

2021-02-17 21:12 UTC, 7ep commented on src/test/kotlin/coverosR3z/timerecording/UITimeEntryTests.kt
> +        val projecta = "projecta"
This was a bear!

2021-02-17 21:12 UTC, 7ep commented on src/test/kotlin/coverosR3z/timerecording/UITimeEntryTests.kt
> -    private fun calcDateString(date : Date) : String {
Moved this to the POM

2021-02-17 21:12 UTC, 7ep commented on src/test/kotlin/coverosR3z/uitests/UITestHelpers.kt
> -    fun enterTime(project: String, time: String, details: String, date: String) {
this is only using view time - not even sure how it landed here.  Moved this to ViewTimePage

2021-02-17 21:12 UTC, 7ep commented on src/test/kotlin/coverosR3z/uitests/UITestHelpers.kt
> +    fun enterTime(project: String, time: String, details: String, date: String) {
A lot of new capabilities in the ViewTimePage

2021-02-18 16:03 UTC, coveros-matt-taylor requested changes

2021-02-18 16:03 UTC, coveros-matt-taylor commented on src/main/kotlin/coverosR3z/timerecording/api/ViewTimeAPI.kt
> +                <input name="${Elements.DATE_INPUT.getElemName()}" type="date" min="$earliestAllowableDate" max="$latestAllowableDate" value="${safeAttr(it.date.stringValue)}" />
We could also dynamically change these bounds to only w/in the current period. If we want...

2021-02-18 16:03 UTC, coveros-matt-taylor commented on src/test/kotlin/coverosR3z/uitests/PageObjectModel.kt
> +        } else {
Return _chrome_ format?

2021-02-18 16:05 UTC, coveros-matt-taylor commented
Looking good!

2021-02-18 16:05 UTC, coveros-matt-taylor approved these changes

2021-02-18 16:07 UTC, merged